# Site settings
title: PostCSS German Style Sheets
email: tim@cheung.io
description: > # this means to ignore newlines until "baseurl:"
  Ever wanted writing your CSS in German or your English is too broken?
  postcss-german-stylesheets lets you write your CSS in German!
  With PostCSS it (nearly) doesn't matter in which environment you're developing.
baseurl: "/postcss-german-stylesheets" # the subpath of your site, e.g. /blog/
url: "http://timche.github.io" # the base hostname & protocol for your site
twitter_username: timche_
github_username:  timche

# Build settings
markdown: kramdown
